package controller;

public enum Actions {
	EXIT_ON_CLOSE, ACCEPT_ADD_PROCESS, CANCEL_ADD_PROCESS, CLOSE_PROCESS_DIALOG, CLOSE_ERROR_DIALOG, ACCEPT_EDIT_PROCESS, CLOSE_EDIT_PROCESS_DIALOG, SIMULATE, CLEAN_ALL, OPEN_REPORT, SHOW_ADD_PROCESS, CLOSE_ADD_PROCESS_DIALOG
}
